name: Build macOS app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install compatible setuptools version
        run: |
          python -m pip install --upgrade pip
          pip install setuptools==57.5.0  # Version stable de setuptools

      - name: Install dependencies
        run: |
          pip install py2app

      - name: Clean previous builds
        run: |
          rm -rf build dist .tox .nox .coverage .hypothesis .pytest_cache

      - name: Build app with verbose logging
        run: |
          python setup.py py2app --verbose